import { DocsRootDir, AccessibilityDir, DesignGuidelinesDir } from './const.js';

export const ComponentsDir = 'components';

export const ComponentDocs = [
  `[@patternfly/AboutModal - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/about-modal/about-modal.md)`,
  `[@patternfly/AboutModal - Accessibility](${AccessibilityDir}/about-modal/about-modal.md)`,
  `[@patternfly/Accordion - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/accordion/accordion.md)`,
  `[@patternfly/Accordion - Accessibility](${AccessibilityDir}/accordion/accordion.md)`,
  `[@patternfly/ActionList - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/action-list/action-list.md)`,
  `[@patternfly/ActionList - Accessibility](${AccessibilityDir}/action-list/action-list.md)`,
  `[@patternfly/Alert - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/alert/alert.md)`,
  `[@patternfly/Alert - Accessibility](${AccessibilityDir}/alert/alert.md)`,
  `[@patternfly/ApplicationLauncher - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/application-launcher/application-launcher.md)`,
  `[@patternfly/ApplicationLauncher - Accessibility](${AccessibilityDir}/application-launcher/application-launcher.md)`,
  `[@patternfly/Avatar - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/avatar/avatar.md)`,
  `[@patternfly/Avatar - Accessibility](${AccessibilityDir}/avatar/avatar.md)`,
  `[@patternfly/BackToTop - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/back-to-top/back-to-top.md)`,
  `[@patternfly/BackToTop - Accessibility](${AccessibilityDir}/back-to-top/back-to-top.md)`,
  `[@patternfly/Backdrop - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/backdrop/backdrop.md)`,
  `[@patternfly/Backdrop - Accessibility](${AccessibilityDir}/backdrop/backdrop.md)`,
  `[@patternfly/BackgroundImage - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/background-image/background-image.md)`,
  `[@patternfly/BackgroundImage - Accessibility](${AccessibilityDir}/background-image/background-image.md)`,
  `[@patternfly/Badge - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/badge/badge.md)`,
  `[@patternfly/Badge - Accessibility](${AccessibilityDir}/badge/badge.md)`,
  `[@patternfly/Banner - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/banner/banner.md)`,
  `[@patternfly/Banner - Accessibility](${AccessibilityDir}/banner/banner.md)`,
  `[@patternfly/Brand - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/brand/brand.md)`,
  `[@patternfly/Brand - Accessibility](${AccessibilityDir}/brand/brand.md)`,
  `[@patternfly/Breadcrumb - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/breadcrumb/breadcrumb.md)`,
  `[@patternfly/Breadcrumb - Accessibility](${AccessibilityDir}/breadcrumb/breadcrumb.md)`,
  `[@patternfly/Button - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/button/button.md)`,
  `[@patternfly/Button - Accessibility](${AccessibilityDir}/button/button.md)`,
  `[@patternfly/CalendarMonth - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/calendar-month/calendar-month.md)`,
  `[@patternfly/CalendarMonth - Accessibility](${AccessibilityDir}/calendar-month/calendar-month.md)`,
  `[@patternfly/Card - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/card/card.md)`,
  `[@patternfly/Card - Accessibility](${AccessibilityDir}/card/card.md)`,
  `[@patternfly/Checkbox - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/checkbox/checkbox.md)`,
  `[@patternfly/Checkbox - Accessibility](${AccessibilityDir}/checkbox/checkbox.md)`,
  `[@patternfly/ChipDeprecated - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/chip-deprecated/chip-deprecated.md)`,
  `[@patternfly/ChipDeprecated - Accessibility](${AccessibilityDir}/chip-deprecated/chip-deprecated.md)`,
  `[@patternfly/ClipboardCopy - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/clipboard-copy/clipboard-copy.md)`,
  `[@patternfly/ClipboardCopy - Accessibility](${AccessibilityDir}/clipboard-copy/clipboard-copy.md)`,
  `[@patternfly/CodeBlock - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/code-block/code-block.md)`,
  `[@patternfly/CodeBlock - Accessibility](${AccessibilityDir}/code-block/code-block.md)`,
  `[@patternfly/CodeEditor - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/code-editor/code-editor.md)`,
  `[@patternfly/CodeEditor - Accessibility](${AccessibilityDir}/code-editor/code-editor.md)`,
  `[@patternfly/Content - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/content/content.md)`,
  `[@patternfly/Content - Accessibility](${AccessibilityDir}/content/content.md)`,
  `[@patternfly/DataList - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/data-list/data-list.md)`,
  `[@patternfly/DataList - Accessibility](${AccessibilityDir}/data-list/data-list.md)`,
  `[@patternfly/DatePicker - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/date-picker/date-picker.md)`,
  `[@patternfly/DatePicker - Accessibility](${AccessibilityDir}/date-picker/date-picker.md)`,
  `[@patternfly/DateTimePicker - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/date-time-picker/date-time-picker.md)`,
  `[@patternfly/DateTimePicker - Accessibility](${AccessibilityDir}/date-time-picker/date-time-picker.md)`,
  `[@patternfly/DescriptionList - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/description-list/description-list.md)`,
  `[@patternfly/DescriptionList - Accessibility](${AccessibilityDir}/description-list/description-list.md)`,
  `[@patternfly/Divider - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/divider/divider.md)`,
  `[@patternfly/Divider - Accessibility](${AccessibilityDir}/divider/divider.md)`,
  `[@patternfly/DragAndDrop - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/drag-and-drop/drag-and-drop.md)`,
  `[@patternfly/DragAndDrop - Accessibility](${AccessibilityDir}/drag-and-drop/drag-and-drop.md)`,
  `[@patternfly/Drawer - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/drawer/drawer.md)`,
  `[@patternfly/Drawer - Accessibility](${AccessibilityDir}/drawer/drawer.md)`,
  `[@patternfly/Dropdown - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/dropdown/dropdown.md)`,
  `[@patternfly/Dropdown - Accessibility](${AccessibilityDir}/dropdown/dropdown.md)`,
  `[@patternfly/DualListSelector - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/dual-list-selector/dual-list-selector.md)`,
  `[@patternfly/DualListSelector - Accessibility](${AccessibilityDir}/dual-list-selector/dual-list-selector.md)`,
  `[@patternfly/EmptyState - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/empty-state/empty-state.md)`,
  `[@patternfly/EmptyState - Accessibility](${AccessibilityDir}/empty-state/empty-state.md)`,
  `[@patternfly/ExpandableSection - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/expandable-section/expandable-section.md)`,
  `[@patternfly/ExpandableSection - Accessibility](${AccessibilityDir}/expandable-section/expandable-section.md)`,
  `[@patternfly/FileUpload - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/file-upload/file-upload.md)`,
  `[@patternfly/FileUpload - Accessibility](${AccessibilityDir}/file-upload/file-upload.md)`,
  `[@patternfly/Form - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/form/form.md)`,
  `[@patternfly/Form - Accessibility](${AccessibilityDir}/form/form.md)`,
  `[@patternfly/FormControl - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/form-control/form-control.md)`,
  `[@patternfly/FormControl - Accessibility](${AccessibilityDir}/form-control/form-control.md)`,
  `[@patternfly/FormSelect - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/form-select/form-select.md)`,
  `[@patternfly/FormSelect - Accessibility](${AccessibilityDir}/form-select/form-select.md)`,
  `[@patternfly/HelperText - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/helper-text/helper-text.md)`,
  `[@patternfly/HelperText - Accessibility](${AccessibilityDir}/helper-text/helper-text.md)`,
  `[@patternfly/Hint - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/hint/hint.md)`,
  `[@patternfly/Hint - Accessibility](${AccessibilityDir}/hint/hint.md)`,
  `[@patternfly/Icon - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/icon/icon.md)`,
  `[@patternfly/Icon - Accessibility](${AccessibilityDir}/icon/icon.md)`,
  `[@patternfly/InlineEdit - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/inline-edit/inline-edit.md)`,
  `[@patternfly/InlineEdit - Accessibility](${AccessibilityDir}/inline-edit/inline-edit.md)`,
  `[@patternfly/InputGroup - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/input-group/input-group.md)`,
  `[@patternfly/InputGroup - Accessibility](${AccessibilityDir}/input-group/input-group.md)`,
  `[@patternfly/JumpLinks - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/jump-links/jump-links.md)`,
  `[@patternfly/JumpLinks - Accessibility](${AccessibilityDir}/jump-links/jump-links.md)`,
  `[@patternfly/Label - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/label/label.md)`,
  `[@patternfly/Label - Accessibility](${AccessibilityDir}/label/label.md)`,
  `[@patternfly/List - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/list/list.md)`,
  `[@patternfly/List - Accessibility](${AccessibilityDir}/list/list.md)`,
  `[@patternfly/LoginPage - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/login-page/login-page.md)`,
  `[@patternfly/LoginPage - Accessibility](${AccessibilityDir}/login-page/login-page.md)`,
  `[@patternfly/Masthead - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/masthead/masthead.md)`,
  `[@patternfly/Masthead - Accessibility](${AccessibilityDir}/masthead/masthead.md)`,
  `[@patternfly/Menu - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/menu/menu.md)`,
  `[@patternfly/Menu - Accessibility](${AccessibilityDir}/menu/menu.md)`,
  `[@patternfly/MenuToggle - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/menu-toggle/menu-toggle.md)`,
  `[@patternfly/MenuToggle - Accessibility](${AccessibilityDir}/menu-toggle/menu-toggle.md)`,
  `[@patternfly/Modal - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/modal/modal.md)`,
  `[@patternfly/Modal - Accessibility](${AccessibilityDir}/modal/modal.md)`,
  `[@patternfly/Navigation - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/navigation/navigation.md)`,
  `[@patternfly/Navigation - Accessibility](${AccessibilityDir}/navigation/navigation.md)`,
  `[@patternfly/NotificationBadge - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/notification-badge/notification-badge.md)`,
  `[@patternfly/NotificationBadge - Accessibility](${AccessibilityDir}/notification-badge/notification-badge.md)`,
  `[@patternfly/NotificationDrawer - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/notification-drawer/notification-drawer.md)`,
  `[@patternfly/NotificationDrawer - Accessibility](${AccessibilityDir}/notification-drawer/notification-drawer.md)`,
  `[@patternfly/NumberInput - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/number-input/number-input.md)`,
  `[@patternfly/NumberInput - Accessibility](${AccessibilityDir}/number-input/number-input.md)`,
  `[@patternfly/OverflowMenu - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/overflow-menu/overflow-menu.md)`,
  `[@patternfly/OverflowMenu - Accessibility](${AccessibilityDir}/overflow-menu/overflow-menu.md)`,
  `[@patternfly/Page - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/page/page.md)`,
  `[@patternfly/Page - Accessibility](${AccessibilityDir}/page/page.md)`,
  `[@patternfly/Pagination - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/pagination/pagination.md)`,
  `[@patternfly/Pagination - Accessibility](${AccessibilityDir}/pagination/pagination.md)`,
  `[@patternfly/Panel - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/panel/panel.md)`,
  `[@patternfly/Panel - Accessibility](${AccessibilityDir}/panel/panel.md)`,
  `[@patternfly/Popover - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/popover/popover.md)`,
  `[@patternfly/Popover - Accessibility](${AccessibilityDir}/popover/popover.md)`,
  `[@patternfly/Progress - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/progress/progress.md)`,
  `[@patternfly/Progress - Accessibility](${AccessibilityDir}/progress/progress.md)`,
  `[@patternfly/ProgressStepper - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/progress-stepper/progress-stepper.md)`,
  `[@patternfly/ProgressStepper - Accessibility](${AccessibilityDir}/progress-stepper/progress-stepper.md)`,
  `[@patternfly/Radio - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/radio/radio.md)`,
  `[@patternfly/Radio - Accessibility](${AccessibilityDir}/radio/radio.md)`,
  `[@patternfly/SearchInput - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/search-input/search-input.md)`,
  `[@patternfly/SearchInput - Accessibility](${AccessibilityDir}/search-input/search-input.md)`,
  `[@patternfly/Select - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/select/select.md)`,
  `[@patternfly/Select - Accessibility](${AccessibilityDir}/select/select.md)`,
  `[@patternfly/Sidebar - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/sidebar/sidebar.md)`,
  `[@patternfly/Sidebar - Accessibility](${AccessibilityDir}/sidebar/sidebar.md)`,
  `[@patternfly/SimpleList - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/simple-list/simple-list.md)`,
  `[@patternfly/SimpleList - Accessibility](${AccessibilityDir}/simple-list/simple-list.md)`,
  `[@patternfly/Skeleton - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/skeleton/skeleton.md)`,
  `[@patternfly/Skeleton - Accessibility](${AccessibilityDir}/skeleton/skeleton.md)`,
  `[@patternfly/SkipToContent - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/skip-to-content/skip-to-content.md)`,
  `[@patternfly/SkipToContent - Accessibility](${AccessibilityDir}/skip-to-content/skip-to-content.md)`,
  `[@patternfly/Slider - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/slider/slider.md)`,
  `[@patternfly/Slider - Accessibility](${AccessibilityDir}/slider/slider.md)`,
  `[@patternfly/Spinner - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/spinner/spinner.md)`,
  `[@patternfly/Spinner - Accessibility](${AccessibilityDir}/spinner/spinner.md)`,
  `[@patternfly/Switch - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/switch/switch.md)`,
  `[@patternfly/Switch - Accessibility](${AccessibilityDir}/switch/switch.md)`,
  `[@patternfly/Table - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/table/table.md)`,
  `[@patternfly/Tabs - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/tabs/tabs.md)`,
  `[@patternfly/Tabs - Accessibility](${AccessibilityDir}/tabs/tabs.md)`,
  `[@patternfly/TextArea - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/text-area/text-area.md)`,
  `[@patternfly/TextArea - Accessibility](${AccessibilityDir}/text-area/text-area.md)`,
  `[@patternfly/TextInput - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/text-input/text-input.md)`,
  `[@patternfly/TextInput - Accessibility](${AccessibilityDir}/text-input/text-input.md)`,
  `[@patternfly/TextInputGroup - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/text-input-group/text-input-group.md)`,
  `[@patternfly/TextInputGroup - Accessibility](${AccessibilityDir}/text-input-group/text-input-group.md)`,
  `[@patternfly/TileDeprecated - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/tile-deprecated/tile-deprecated.md)`,
  `[@patternfly/TileDeprecated - Accessibility](${AccessibilityDir}/tile-deprecated/tile-deprecated.md)`,
  `[@patternfly/TimePicker - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/time-picker/time-picker.md)`,
  `[@patternfly/TimePicker - Accessibility](${AccessibilityDir}/time-picker/time-picker.md)`,
  `[@patternfly/Timestamp - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/timestamp/timestamp.md)`,
  `[@patternfly/Timestamp - Accessibility](${AccessibilityDir}/timestamp/timestamp.md)`,
  `[@patternfly/Title - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/title/title.md)`,
  `[@patternfly/Title - Accessibility](${AccessibilityDir}/title/title.md)`,
  `[@patternfly/ToggleGroup - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/toggle-group/toggle-group.md)`,
  `[@patternfly/ToggleGroup - Accessibility](${AccessibilityDir}/toggle-group/toggle-group.md)`,
  `[@patternfly/Toolbar - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/toolbar/toolbar.md)`,
  `[@patternfly/Toolbar - Accessibility](${AccessibilityDir}/toolbar/toolbar.md)`,
  `[@patternfly/Tooltip - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/tooltip/tooltip.md)`,
  `[@patternfly/Tooltip - Accessibility](${AccessibilityDir}/tooltip/tooltip.md)`,
  `[@patternfly/TreeView - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/tree-view/tree-view.md)`,
  `[@patternfly/TreeView - Accessibility](${AccessibilityDir}/tree-view/tree-view.md)`,
  `[@patternfly/Truncate - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/truncate/truncate.md)`,
  `[@patternfly/Truncate - Accessibility](${AccessibilityDir}/truncate/truncate.md)`,
  `[@patternfly/Wizard - Design Guidelines](${DesignGuidelinesDir}/${ComponentsDir}/wizard/wizard.md)`,
  `[@patternfly/Wizard - Accessibility](${AccessibilityDir}/wizard/wizard.md)`,
];
